service: pfa

plugins:
  - serverless-dotenv-plugin

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  iam:
    role:
      statements:
        - Effect: 'Allow'
          Action:
            - 'ec2:DescribeNetworkInterfaces'
            - 'ec2:CreateNetworkInterface'
            - 'ec2:DeleteNetworkInterface'
            - 'ec2:DescribeNetworkInterfaces'
            - 'ec2:DescribeNetworkInterfaces'
          Resource:
            - '*'

package:
  patterns:
    - 'lib/**'
    - '!node_modules'
    - '!dist'
    - '!src/**'

functions:
  create-product-request:
    handler: lib/handler.ProductRequest.Handlers.createProductRequest
    vpc:
      securityGroupIds:
        - sg-0f83d270911584b4c
      subnetIds:
        - subnet-00564fda019d88698
        - subnet-0046df74f473dbff1
        - subnet-0df34d52d49b6c014
        - subnet-0f93f5be6d905d401
        - subnet-0077e3750c924d19d
        - subnet-0c6cb803a4b7db664
    events:
      - http:
          path: product-request/create
          method: POST
          cors: true
